kind = "web"
previewPath = "/"
title = "FARIZAL COFFE"
version = "1.0.0"
id = "artifacts/farizal-coffe"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25777

[services.development]
run = "pnpm --filter @workspace/farizal-coffe run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/farizal-coffe", "run", "build" ]
publicDir = "artifacts/farizal-coffe/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25777"
BASE_PATH = "/"
